const ANALYTICS_CONSTANTS = {
  CHECKOUT_STEP: "TRIGGER_CHECKOUT_STEP",
};

const ALERT_CONSTANTS = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  SECONDARY: "ALERT_SECONDARY",
  CLEAR: "ALERT_CLEAR",
  WARNING: "ALERT_WARNING",
  INFO: "ALERT_INFO",
};

const ACTION_CONSTANTS = {
  TERMS_OPEN: "DIALOG_OPEN_REQUEST",
  TERMS_CLOSE: "DIALOG_CLOSE_REQUEST",

  MODAL_OPEN: "MODAL_OPEN_REQUEST",
  MODAL_REOPEN: "MODAL_REOPEN_REQUEST",
  MODAL_CLOSE: "MODAL_CLOSE_REQUEST",

  ORDER_EXPIRED: "ORDER_STATUS_EXPIRED",
  SHOW_PAGE_LOADER: "SHOW_PAGE_LOADER",
};

const ERROR_CONSTANTS = {
  ERROR: "ERROR_SCREEN",
  MESSAGE: "ERROR_MESSAGE",
};

const FORM_CONSTANTS = {
  LOGOUT: "LOGOUT",

  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_PLEASE_WAIT_LOADER: "",

  NO_INTERNET_CONNECTION: "NO_INTERNET_CONNECTION",
};

export {
  ALERT_CONSTANTS,
  ACTION_CONSTANTS,
  ANALYTICS_CONSTANTS,
  ERROR_CONSTANTS,
  FORM_CONSTANTS,
};
