import { ROUTE_CONSTANTS } from "./utils";

import {
  Home,
  Shop,
  SignUp,
  Dashboard,
  LoginMobileVerification,
  LoginOtpVerification,
  EditClosetProducts,
  Page404,
  Category,
  CheckoutPage,
  FaqPage,
  Closet,
  Cart,
  Profile,
  Review,
  Search,
  TermsPage,
  Wishlist,
  PrivacyPage,
  ProductDetail,
  Contact,
  AboutUs,
} from "./containers";

const routes = [
  {
    path: ROUTE_CONSTANTS.BASE,
    exact: true,
    component: Home,
    protected: false,
    default: false,
    view: "Base",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.SHOP,
    exact: true,
    component: Shop,
    protected: false,
    default: false,
    view: "Shop",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.SIGNUP,
    exact: true,
    component: SignUp,
    protected: false,
    default: false,
    view: "Sign Up",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CREATE_CLOSET,
    exact: true,
    component: SignUp,
    protected: false,
    default: false,
    view: "Create Closet",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CATEGORY,
    exact: true,
    component: Category,
    protected: false,
    default: false,
    view: "Category",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CATEGORY,
    exact: true,
    component: Category,
    protected: false,
    default: false,
    view: "Category",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CHECKOUT,
    exact: true,
    component: CheckoutPage,
    protected: false,
    default: false,
    view: "Checkout",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.FAQ,
    exact: true,
    component: FaqPage,
    protected: false,
    default: false,
    view: "FAQ",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CLOSET,
    exact: true,
    component: Closet,
    protected: false,
    default: false,
    view: "Closet",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CART,
    exact: true,
    component: Cart,
    protected: false,
    default: false,
    view: "Cart",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.PROFILE,
    exact: true,
    component: Profile,
    protected: false,
    default: false,
    view: "Profile",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.REVIEW,
    exact: true,
    component: Review,
    protected: false,
    default: false,
    view: "Review",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.SEARCH,
    exact: true,
    component: Search,
    protected: false,
    default: false,
    view: "Search",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.TERMS,
    exact: true,
    component: TermsPage,
    protected: false,
    default: false,
    view: "Terms",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.WISHLIST,
    exact: true,
    component: Wishlist,
    protected: false,
    default: false,
    view: "Wishlist",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.PRIVACY,
    exact: true,
    component: PrivacyPage,
    protected: false,
    default: false,
    view: "Privacy",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.PRODUCTDETAIL,
    exact: true,
    component: ProductDetail,
    protected: false,
    default: false,
    view: "ProductDetail",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.CONTACT,
    exact: true,
    component: Contact,
    protected: false,
    default: false,
    view: "Contact",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.ABOUTUS,
    exact: true,
    component: AboutUs,
    protected: false,
    default: false,
    view: "AboutUs",
    allowBack: false,
  },
  {
    path: ROUTE_CONSTANTS.ANY,
    exact: false,
    component: Page404,
    protected: false,
    default: false,
    view: "*",
    allowBack: false,
  },
];
export default routes;
